# Generated by Django 5.2.6 on 2026-06-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='question',
            new_name='query',
        ),
    ]
