# Generated by Django 5.2.6 on 2026-06-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_retrievedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='RetrievedImage',
        ),
    ]
